[package]
name = "asure-pension-core"
version = "0.1.0"
authors = ["pmizel <pmizel@echtnice.com>"]
edition = "2018"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
chrono = "0.4"
csv = "1.0"
serde = "1.0"
serde_derive = "1.0"
